//
// Created by iron on 2019/11/18.
//

#ifndef STOREBENCHMARK_DATADESC_H
#define STOREBENCHMARK_DATADESC_H

#define ORDERKEY_LEN 8
#define PARTKEY_LEN 6
#define SUPPKEY_LEN 5
#define LINENUMBER_LEN 1
#define LINEITEM_KEY_LEN 21

#define EXTENDPRICE_LEN 9
#define SHIPINSTRUCT_LEN 17
#define SHIPMODE_LEN 7
#define COMMENT_LEN 43
#define LINEITEM_VALUE_LEN 128

#define ID1_LEN 5
#define USERINFORM_KEY_LEN 5
#define USERINFORM_VALUE_LEN 34
#define NAME_LEN 6
#define AGE_LEN 4
#define GENDER_LEN 1
#define OCCUPATION_LEN 15
#define REGISTER_DATE_LEN 8

#define ID2_LEN 6
#define UID_LEN 5
#define LOG_TIME_LEN 9
#define IP_LEN 16
#define DEVICE_LEN 13
#define USERBEHAVIOR_KEY_LEN 6
#define USERBEHAVIOR_VALUE_LEN 43
#endif //STOREBENCHMARK_DATADESC_H
